---
kind: pipeline
type: ssh
name: build

server:
  host: ec2-54-196-230-184.compute-1.amazonaws.com
  user: ubuntu
  password:
    from_secret: password

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: configurations
    depends_on: [clone]
    commands:
      - sudo docker login --username nob786 --password Ilovepak786

  - name: build-api-gateway
    depends_on: [configurations]
    commands:
      - cd api-gateway
      - sudo docker build -t api-gateway:latest .
      - sudo docker tag api-gateway:latest nob786/mc:api-gateway${DRONE_COMMIT:0:7}
      - sudo docker push nob786/mc:api-gateway${DRONE_COMMIT:0:7}
      - sudo docker image rm -f api-gateway:latest
      - sudo docker image rm -f nob786/mc:api-gateway${DRONE_COMMIT:0:7}

  - name: build-auth-service
    depends_on: [build-api-gateway]
    commands:
      - cd auth-service
      - sudo docker build -t auth-service:latest .
      - sudo docker tag auth-service:latest nob786/mc:auth-service${DRONE_COMMIT:0:7}
      - sudo docker push nob786/mc:auth-service${DRONE_COMMIT:0:7}
      - sudo docker image rm -f auth-service:latest
      - sudo docker image rm -f nob786/mc:auth-service${DRONE_COMMIT:0:7}

  - name: build-customer-service
    depends_on: [build-auth-service]
    commands:
      - cd customer-service
      - sudo docker build -t customer-service:latest .
      - sudo docker tag customer-service:latest nob786/mc:customer-service${DRONE_COMMIT:0:7}
      - sudo docker push nob786/mc:customer-service${DRONE_COMMIT:0:7}
      - sudo docker image rm -f customer-service:latest
      - sudo docker image rm -f nob786/mc:customer-service${DRONE_COMMIT:0:7}

  - name: build-restaurant-service
    depends_on: [build-customer-service]
    commands:
      - cd restaurant-service
      - sudo docker build -t restaurant-service:latest .
      - sudo docker tag restaurant-service:latest nob786/mc:restaurant-service${DRONE_COMMIT:0:7}
      - sudo docker push nob786/mc:restaurant-service${DRONE_COMMIT:0:7}
      - sudo docker image rm -f restaurant-service:latest
      - sudo docker image rm -f nob786/mc:restaurant-service${DRONE_COMMIT:0:7}

  # - name: build-client-service
  #   depends_on: [build-restaurant-service]
  #   commands:
  #     - cd client
  #     - sudo docker build -t client-service:latest .
  #     - sudo docker tag client-service:latest nob786/mc:client-service${DRONE_COMMIT:0:7}
  #     - sudo docker push nob786/mc:client-service${DRONE_COMMIT:0:7}
  #     - sudo docker image rm -f nob786/mc:client-service${DRONE_COMMIT:0:7}
